unstable_features = true
max_width = 100
group_imports = "One"
struct_lit_single_line = false
reorder_impl_items = true
imports_granularity = "Module"
use_field_init_shorthand = true
edition = "2021"
